name: Docker Image CI
on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Copy env.example to .env
        run: cp env.example .env

      - name: Start services with Docker Compose
        run: docker-compose up -d --build

      - name: Wait for the database to be ready
        run: |
          echo "Waiting for database to be ready..."
          for i in {1..30}; do
            docker inspect --format='{{.State.Health.Status}}' jurnalyuga_db | grep -q "healthy" && break
            sleep 2
          done

      - name: Run tests
        run: docker-compose exec -T backend sh -c "PYTHONPATH=\$(pwd) poetry run pytest -sv tests/"

      - name: Stop and remove containers
        run: docker-compose down
